version: '3.8' 

services:
  web: 
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - ./secrets/chave.json:/app/secrets/gcp_key.json:ro      
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp_key.json
